spring:
    main:
        banner-mode: off
    datasource:
        url: ${POSTGRES_URL}
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        generate-ddl: true
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
logging:
    level:
        org.springframework.security: debug