spring:
    main:
        banner-mode: off
    datasource:
        url: jdbc:postgresql://localhost:5432/tnp
        username: postgres
        password: rodrigo
        driver-class-name: org.postgresql.Driver
    jpa:
        generate-ddl: true
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
logging:
    level:
        org.springframework.security: debug